#!/bin/bash
#PBS -l walltime=00:30:00
#PBS -l mem=50G
#PBS -l ncpus=1
#PBS -l wd
#PBS -q normal
#PBS -P project
#PBS -l storage=gdata/<project1>+scratch/<project1>+gdata/<project2>+scratch/<project2>

# Load necessary modules
module load bwa

# Create a soft link to the reference genome in the current working directory
ln -s /path/to/sample_hap1_clean.fasta .
# Index the genome using the symlink in the current directory
bwa index sample_hap1_clean.fasta

