#!/bin/bash
#PBS -l walltime=3:00:00
#PBS -l mem=50G
#PBS -l ncpus=1
#PBS -l wd
#PBS -q normal
#PBS -P project
#PBS -l storage=gdata/<project1>+scratch/<project1>+gdata/<project2>+scratch/<project2>

# Load required modules
module load python3

# Set paths to datasets
dataset1="sampple_hap1_clean.fasta"
dir1="/path/to/sample_hap1_clean.fasta"
dataset2="sample_hap2_clean.fasta"
dir2="/path/to/sample_hap2_clean.fasta"

# Run generate_site_positions.py for dataset1
python3 /path/to/juicer/misc/generate_site_positions.py Arima "$dataset1" "$dir1"
python3 /path/to/juicer/misc/generate_site_positions.py Arima "$dataset2" "$dir2"
mv sample_hap2* /path/to/restriction_sites/
# Run generate_site_positions.py for dataset2
#python3 /path/to/juicer/misc/generate_site_positions.py MboI "$dataset2" /path/to/juicer/references/hap2_hic.fasta

