#!/bin/bash
#PBS -l walltime=1:00:00
#PBS -l mem=5G
#PBS -l ncpus=1
#PBS -l software=amber
#PBS -l wd
#PBS -q normal
#PBS -P project
#PBS -l storage=gdata/<project1>+scratch/<project1>+gdata/<project2>+scratch/<project2>
hic_1="/path/to/fastq/R1.fastq"
hic_2="/path/to/fastq/R2.fastq"
split -a 3 -l 20000000 -d --numeric-suffixes --additional-suffix=_R1.fastq $hic_1
split -a 3 -l 20000000 -d --numeric-suffixes --additional-suffix=_R2.fastq $hic_2
