#!/bin/bash
#PBS -l walltime=08:00:00
#PBS -l mem=80G
#PBS -l ncpus=24
#PBS -l wd
#PBS -q normal
#PBS -P project
#PBS -l storage=gdata/<project1>+scratch/<project1>+gdata/<project2>+scratch/<project2>
# Export updated Java options
export _JAVA_OPTIONS="-Xmx150G -Xms150G"

# Load necessary modules
module load java bwa samtools

# Set working directory and paths
juicer_dir="/path/to/sample_hap1/" 
chrom_sizes="chrom_sizes_sample_hap1" 
reference_genome="references/sample_hap1_clean.fasta" 
enzyme_file="restriction_sites/sample_hap1_clean.fasta_Arima.txt" 
juicer_script="/path/to/juicer/PBS/scripts/juicer.sh"

# Run juicer
$juicer_script -d "$juicer_dir" \
               -t 24 \
               -p "$chrom_sizes" \
               -s Arima \
               -z "$reference_genome" \
               -y "$enzyme_file" \
	       -g "sample_hap1_clean"  

# Notify completion
echo "Juicer pipeline completed successfully!"

