name: hic-pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - bwa-mem2=2.2.1
  - samtools=1.15
  - samblaster=0.1.25
  - hicexplorer=3.7
  - cooler
  - bedtools=2.30
  - python>=3.8
  - r-base>=4.1
  - r-ggplot2
  - r-dplyr
  - circos
